In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [ ]:
df=pd.read_csv("/content/drive/My Drive/Data sets/BankCreditCard.csv")

In [ ]:
print(df.head())

   Customer ID  Credit_Amount  ...  Previous_Payment_June  Default_Payment
0            1        20000.0  ...                    0.0                1
1            2       220000.0  ...                 2000.0                1
2            3        90000.0  ...                 5000.0                0
3            4        50000.0  ...                 1000.0                0
4            5        50000.0  ...                  679.0                0

[5 rows x 25 columns]


In [ ]:
df.isnull().sum()

Customer ID               0
Credit_Amount             0
Gender                    0
Academic_Qualification    0
Marital                   0
Age_Years                 0
Repayment_Status_Jan      0
Repayment_Status_Feb      0
Repayment_Status_March    0
Repayment_Status_April    0
Repayment_Status_May      0
Repayment_Status_June     0
Jan_Bill_Amount           0
Feb_Bill_Amount           0
March_Bill_Amount         0
April_Bill_Amount         0
May_Bill_Amount           0
June_Bill_Amount          0
Previous_Payment_Jan      0
Previous_Payment_Feb      0
Previous_Payment_March    0
Previous_Payment_April    0
Previous_Payment_May      0
Previous_Payment_June     0
Default_Payment           0
dtype: int64

In [ ]:
df.dtypes

Customer ID                 int64
Credit_Amount             float64
Gender                      int64
Academic_Qualification      int64
Marital                     int64
Age_Years                   int64
Repayment_Status_Jan        int64
Repayment_Status_Feb        int64
Repayment_Status_March      int64
Repayment_Status_April      int64
Repayment_Status_May        int64
Repayment_Status_June       int64
Jan_Bill_Amount           float64
Feb_Bill_Amount           float64
March_Bill_Amount         float64
April_Bill_Amount         float64
May_Bill_Amount           float64
June_Bill_Amount          float64
Previous_Payment_Jan      float64
Previous_Payment_Feb      float64
Previous_Payment_March    float64
Previous_Payment_April    float64
Previous_Payment_May      float64
Previous_Payment_June     float64
Default_Payment             int64
dtype: object

In [ ]:
df.shape

(30000, 25)

In [ ]:
X = df.iloc[:, 0:25].values
y = df.iloc[:, -1].values

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
ann = tf.keras.models.Sequential()

In [ ]:
ann.add(tf.keras.layers.Dense(units=6,activation="relu"))

In [ ]:
ann.add(tf.keras.layers.Dense(units=6,activation="relu"))

In [ ]:
ann.add(tf.keras.layers.Dense(units=1,activation="sigmoid"))

In [ ]:
ann.compile(optimizer="adam",loss="binary_crossentropy", metrics=["accuracy"])

In [ ]:
ann.fit(X_train,y_train, batch_size=32, epochs=100)

Epoch 1/100
750/750 [==============================] - 2s 2ms/step - loss: 0.3626 - accuracy: 0.8466
Epoch 2/100
750/750 [==============================] - 2s 2ms/step - loss: 0.0203 - accuracy: 0.9990
Epoch 3/100
750/750 [==============================] - 2s 2ms/step - loss: 0.0039 - accuracy: 0.9997
Epoch 4/100
750/750 [==============================] - 2s 2ms/step - loss: 0.0012 - accuracy: 1.0000
Epoch 5/100
750/750 [==============================] - 2s 2ms/step - loss: 4.9639e-04 - accuracy: 1.0000
Epoch 6/100
750/750 [==============================] - 2s 2ms/step - loss: 2.4409e-04 - accuracy: 1.0000
Epoch 7/100
750/750 [==============================] - 2s 2ms/step - loss: 1.3526e-04 - accuracy: 1.0000
Epoch 8/100
750/750 [==============================] - 2s 2ms/step - loss: 7.8974e-05 - accuracy: 1.0000
Epoch 9/100
750/750 [==============================] - 2s 2ms/step - loss: 4.7517e-05 - accuracy: 1.0000
Epoch 10/100
750/750 [==============================] - 2s 2ms/step - l

In [ ]:
y_pred=ann.predict(X_test)
y_pred=(y_pred>0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [1 1]
 [0 0]
 [0 0]]


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score=(y_test,y_pred)

[[4703    0]
 [   0 1297]]


In [ ]:
accuracy_score

(array([0, 0, 0, ..., 1, 0, 0]), array([[False],
        [False],
        [False],
        ...,
        [ True],
        [False],
        [False]]))